;OBJECTIVE: TO STORE 5 WORDS STARTING FROM 50TH BYTE OF SEGMENT, AND FIND AND STORE THE 2'S COMPLEMENT STARTING FROM 60TH BYTE OF THE SEGMENT
;APPROACH:- BY INITIALIZING FIRST 49 BYTES WE STORE THE WORDS AT 50TH BYTE
;           USING FORMULA 2'S COMPLEMENT = 1'S COMPLEMENT + 1 WHERE 1'S COMPLEMENT = R^n - N, WHERE n IS THE NUMBER OF DIGITS IN N

DATA SEGMENT                                        ;START OF DATA SEGMENT
    EMPTY DB 49 DUP(?)                              ;INITIALIZING FIRST 49 BYTES OF THE SEGMENT
    AWORDS DW 1010B, 1100B, 1101B, 0101B, 1001B     ;STORING THE 5 WORDS IN AN ARRAY STARTING FROM 50TH BYTE OF THE SEGMENT
    RESULT DW ?,?,?,?,?                             ;STORING THE RESULT OF THE COMPLEMENT IN AN ARRAY STORING FROM 60TH BYTE OF SEGMENT
DATA ENDS                                           ;DATA SEGMENT ENDS HERE
CODE SEGMENT                                        ;START OF CODE SEGMENT
    ASSUME: DS: DATA, CS: CODE                      ;ASSOCIATING THE SEGMENT REGISTERS WITH THEIR CORRESPONDING SEGMENTS
    START:                                          ;STARTING OF THE EXECUTION OF CODE SEGMENT
        MOV AX, DATA                                ;TRANSFERING THE OFFSET ADDRESS OF DATA SEGMENT TO AX 
        MOV DS, AX                                  ;TRANSFERING THE AX VALUE TO DS REGISTER IN TOTAL WE TRANSFERED THE VALUE OF DATA TO DS
        MOV SI,0                                    ;INITIALIZING THE VALUE OF SI WITH 0
        MOV CX,5                                    ;INITIALIZING THE VALUE OF CX WITH 5 BECAUSE 5 WORDS SO 5 TIMES LOOP WILL RUN
        LEA BX,AWORDS                               ;STORING THE OFFSET OF AWORDS IN BX REGISTER
                                                    
    COMP:                                           ;LOOP LABEL IS DEFINED AS COMP
        MOV DX,BX[SI]                               ;MOVING A WORD FROM THE ARRAY AWORDS INTO DX OF WHICH 2'S COMPLEMENT TO BE FIND OUT
        MOV AX,1111B                                ;MOVING THE 1111B IN AX FOR PERFORMING THE FIRST OPERATION AS 2'S COMPLEMENT= 1'S COMPLEMENT + 1 
        SUB AX,DX                                   ;SUBTRACTING THE DX FROM AX TO GET THE 1'S COMPLEMENT OF THE WORD
        MOV DX,0001B                                ;MOVING 0001B INTO DX FOR ADDING IT WITH 1'S COMPLEMENT
        ADD AX,DX                                   ;ADDING THE 0001B TO WORD AND WE GET THE 2'S COMPLEMENT
        MOV RESULT[SI],AX                           ;STORING THE RESULT IN THE RESULT ARRAY
        ADD SI,2                                    ;INCREMENTING SI BY 2 BECAUSE OF WORD 
        LOOP COMP                                   ;REPEAT COMP IF CX IS NOT EQUAL TO ZERO ELSE IT WILL MOVE OUT OF THE LOOP
CODE ENDS                                           ;CODE SEGMENT ENDS HERE
END START                                           ;PROGRAM EXECUTION ENDS