;OBJECTIVE:- USING LINEAR SEARCH FIND WHETHER A GIVEN NUMBER IS THERE IN THE SET OF ELEMENTS OR NOT
;APPROACH: COMPARE THE NUMBER TO BE SEARCHED WITH EVERY ELEMENT OF ARRAY IF NUMBER MATCHED THEN NUMBER FOUND ELSE NUMBER NOT FOUND 

DATA SEGMENT                                ;START OF DATA SEGMENT
    ARRAY DB 03H,19H,25H,18H,05H            ;INITIALIZING THE BYTE ARRAY WITH HARD CODED VALUES
    SRCH DB 19H                             ;INITIALIZING THE NUMBER TO BE SEARCHED WITH HARD CODED VALUE
DATA ENDS                                   ;DATA SEGMENT ENDS HERE
CODE SEGMENT                                ;START OF CODE SEGMENT
    ASSUME DS: DATA, CS: CODE               ;ASSOCIATING THE SEGMENT REGISTERS WITH THEIR CORRESPONDING SEGMENTS
    START:                                  ;STARTING OF THE EXECUTION OF CODE SEGMENT
        MOV AX,DATA                         ;TRANSFERING THE OFFSET ADDRESS OF DATA SEGMENT TO AX 
        MOV DS,AX                           ;TRANSFERING THE AX VALUE TO DS REGISTER IN TOTAL WE TRANSFERED THE VALUE OF DATA TO DS
        MOV CX,4                            ;INITIALIZING CX WITH VALUE 4
        MOV SI,0                            ;INITIALIZING SI WITH VALUE 0
        
    SEARCH:                                 ;LOOP LABEL IS DEFINED AS SEARCH
        MOV AL, ARRAY[SI]                   ;MOVING THE ELEMENT OF THE ARRAY INTO AL
        CMP AL, SRCH                        ;COMPARING THE NUMBER TO BE SEARCHED WITH THE ELEMENT OF ARRAY
        JE FOUND                            ;IF NUMBER FOUND THEN THE RESULT WILL BE ZERO SO IT WILL JUMP TO FOUND
        INC SI                              ;ELSE CONTINUE HERE AND INCREMENT SI 
        LOOP SEARCH                         ;REPEAT SEARCH IF CX IS NOT EQUAL TO ZERO ELSE IT WILL MOVE OUT OF THE LOOP
        
        MOV BL,00H                          ;USING 00H TO INDICATE NUMBER NOT FOUND SO STORING IT IN BL
        MOV AX,4C00H                        ;STORING SERVICE NUMBER 4C00H IN AX
        INT 21H                             ;CALLING INTERRUPT TO TERMINATE
    
    FOUND:                                  ;LOOP LABEL IS DEFINED AS FOUND
        MOV BL,01H                          ;USING 01H TO INDICATE NUMBER NOT FOUND SO STORING IT IN BL
        MOV AX,4C00H                        ;STORING SERVICE NUMBER 4C00H IN AX
        INT 21H                             ;CALLING INTERRUPT TO TERMINATE
CODE ENDS                                   ;CODE SEGMENT ENDS HERE
END START                                   ;PROGRAM ENDS